name: Analyze (Snyk)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 12 * * 1

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/build
      with:
        skip-tests: true

    - uses: snyk/actions/dotnet@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: >-
          --all-projects
          --detection-depth=8
          --severity-threshold=high
          --sarif-file-output=snyk.sarif
        command: test

    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
